### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by jesse-wei**

### CODE REVIEW

**Comment by jesse-wei** [comment]
[2048](https://eric-unc.tech/2048) is pretty cool.

image

**Comment by eric-unc** [comment]
idk why you deleted this but thanks ig

**Comment by jesse-wei** [comment]
> idk why you deleted this but thanks ig

I deleted my fork, didn't know that would close the pull request.

**Comment by eric-unc** [comment]
Kinda weird tbh, don't know why it's necessary to close the PR if a patch/diff is still saved for my viewing (/don't think it is necessary)

**Pull request closed without merging**
